### ISSUE TITLE
`EsbIrq` is `!Send`

### ISSUE THREAD

**Issue by jamesmunns** [thalesfragoso/esb#6]
As of the currently released version of `BBQueue`, `FrameGrantR` and `FrameGrantW` are not `Send`. Since `EsbIrq` contains types (within `Option`s), it is also `!Send`.

This means we can't send the handle to the interrupt, which will be a problem for `cmim` and `rtfm`. There are two main ways to fix this:

1. I have PR that makes these grants `Send` by reworking the internals of `BBQueue` to be a little more thread safe. The PR is here: https://github.com/jamesmunns/bbqueue/pull/58. I just need to fix the tests, which work locally, however time out on TravisCI.
2. We can remove the grants from the handle, and expect the user to hold on to these inside of their interrupt handler function.

I think we'll probably go with option 1, but I wanted to write this up in case you run into it before I do. If you do, feel free to switch to a git dependency of bbqueue on PR I linked.

**Comment by thalesfragoso** [comment]
I don't think `2` would work, since it would be really brittle and even maybe unsafe for the users to handle them.

We can totally wait for `1` though, no problem. Also you might want to try out GHA to see if it solves your problem.
